name: catalogue
on: 
 workflow_dispatch:
  inputs:
   project:
    type: string
    required: true
    description: "enter project name"
    default: false

   component:
    type: string
    required: true
    description: "enter component name"
    default: false

   environment:
    type: environment
    required: true
    description: "select environment"

jobs:
  run-ci-pipeline:
     if: github.ref == 'refs/heads/main'
     uses: chara-cicd/usable-workflow/.github/workflows/nodejs.yaml@main
     with: 
       project: ${{ inputs.project }}
       component: ${{ inputs.component }}
       environment: ${{ inputs.environment }}

