name: catalogue
on: 
 workflow_dispatch:
  inputs:
   project:
    type: string
    required: true
    description: "enter project name"

   component:
    type: string
    required: true
    description: "enter component name"

   environment:
    type: environment
    required: true
    description: "select environment"

jobs:
  run-ci-pipeline:
     if: github.ref != 'refs/heads/main'
     uses: chakra-cicd/usable-workflow/.github/workflows/feature-nodejs.yaml@main
     with: 
       project: ${{ inputs.project }}
       component: ${{ inputs.component }}
       environment: ${{ inputs.environment }}
     secrets: inherit