name: catalogue
on: [push]
permissions:
  contents: read
  statuses: write
  security-events: read


jobs:
  run-ci-pipeline:
     if: github.ref != 'refs/heads/main'
     permissions:
       contents: read
       statuses: write
       security-events: read
     uses: chakra-cicd/usable-workflow/.github/workflows/feature-nodejs.yaml@main
     with: 
       project: roboshop
       component: catalogue
       environment: dev
     secrets: inherit